### ISSUE TITLE
How to suppress a lot of warning informations

### ISSUE THREAD

**Issue by qgh1223** [ShengkaiWu/IoU-aware-single-stage-object-detector#2]
How to suppress a lot of warning informations?It caused the google colaboratory colapse

**Comment by qgh1223** [comment]
/pytorch/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.
like this

**Comment by ShengkaiWu** [comment]
Have you installed MMDetection as the guideline? 
![图片](https://user-images.githubusercontent.com/26599885/82990541-f2c29680-a02e-11ea-8a59-f64a5fe6ca83.png)
You'd better state your problem clearly like what command you have executed, the exact error information outputed by the terminal.
