### ISSUE TITLE
IoU-aware在Guided Anchor和FCOS上的效果

### ISSUE THREAD

**Issue by zteddy** [ShengkaiWu/IoU-aware-single-stage-object-detector#4]
您好，在mmdet/models/anchor_heads看到你们不仅试了retina-net上的IoU-aware的效果，好像还试了在Guided Anchor和FCOS上IoU-aware的效果。不知道方不方便交流一下这两个实验的结果？比如FCOS原本已经有了Centerness，我看您在代码里比较了Centerness和IoU score，很好奇有什么收获。

**Comment by ShengkaiWu** [comment]
你好，1）对于Guided anchor，设计IoU prediction，训练时如果target IoU不计算梯度时，可提高AP 0.5%，如果target IoU计算梯度时，性能应该会有进一步的提升，因为target IoU计算梯度这个trick是后面想到的，当时没有做这个实验。2）对于FCOS，其设计的centerness branch也是为了提高定位精度，但是如果将centerness branch替换为IoU prediction branch，模型性能会提高AP 0.4%。

**Comment by zteddy** [comment]
谢谢分享！
