### ISSUE TITLE
预测出来的IoU和真实IoU的对比？

### ISSUE THREAD

**Issue by zjhdxh** [ShengkaiWu/IoU-aware-single-stage-object-detector#5]
作者您好，我想请问一下你们有没有做过基于你们预测出来的IoU和真实的IoU的对比，以此来看看预测出来的IoU准不准确。我自己做的实验结果是预测出来的IoU并不是非常准确，整体会偏高。由于训练的时候并没有回归neg proposal的IoU，导致预测的结果基本都大于0.5。

**Comment by ShengkaiWu** [comment]
你好，我在论文里面比较了采用真实IoU和预测IoU两种情况时模型的性能，如下表所示，性能差异非常大，说明IoU预测地并不准确，如果能够提高预测的IoU的准确度，模型的性能还有大幅的提升空间，但是如何提高预测IoU的准确度目前我还没有很好的思路。

![图片](https://user-images.githubusercontent.com/26599885/88457762-b3dc8000-cebb-11ea-9215-9da26592fc65.png)
![图片](https://user-images.githubusercontent.com/26599885/88457809-146bbd00-cebc-11ea-8721-10aa459fda67.png)

**Comment by zjhdxh** [comment]
感谢你的回复
